/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gabrielle.ddutra
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMenu = new javax.swing.JMenu();
        itmSubmissao = new javax.swing.JMenuItem();
        itmAvaliacao = new javax.swing.JMenuItem();
        itmProgramacao = new javax.swing.JMenuItem();
        itmIngressos = new javax.swing.JMenuItem();
        itmEventos = new javax.swing.JMenuItem();
        mnuLogin = new javax.swing.JMenuItem();
        mnuCadastro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        getContentPane().setLayout(null);

        mnuMenu.setText("MENU");

        itmSubmissao.setText("Submissão");
        itmSubmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSubmissaoActionPerformed(evt);
            }
        });
        mnuMenu.add(itmSubmissao);

        itmAvaliacao.setText("Avaliação");
        itmAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAvaliacaoActionPerformed(evt);
            }
        });
        mnuMenu.add(itmAvaliacao);

        itmProgramacao.setText("Programação");
        itmProgramacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmProgramacaoActionPerformed(evt);
            }
        });
        mnuMenu.add(itmProgramacao);

        itmIngressos.setText("Ingressos");
        itmIngressos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmIngressosActionPerformed(evt);
            }
        });
        mnuMenu.add(itmIngressos);

        itmEventos.setText("Eventos");
        itmEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEventosActionPerformed(evt);
            }
        });
        mnuMenu.add(itmEventos);

        mnuLogin.setText("LOGIN");
        mnuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoginActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuLogin);

        mnuCadastro.setText("CADASTRO");
        mnuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuCadastro);

        jMenuBar1.add(mnuMenu);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(762, 433));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmProgramacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmProgramacaoActionPerformed
        new Programacao().setVisible(true);
    }//GEN-LAST:event_itmProgramacaoActionPerformed

    private void itmSubmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSubmissaoActionPerformed
        new Submissao().setVisible(true);
    }//GEN-LAST:event_itmSubmissaoActionPerformed

    private void itmAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAvaliacaoActionPerformed
        new Avaliacao().setVisible(true);
    }//GEN-LAST:event_itmAvaliacaoActionPerformed

    private void itmIngressosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmIngressosActionPerformed
        new Ingressos().setVisible(true);
    }//GEN-LAST:event_itmIngressosActionPerformed

    private void itmEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEventosActionPerformed
        new Eventos().setVisible(true);
    }//GEN-LAST:event_itmEventosActionPerformed

    private void mnuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoginActionPerformed
        new Login().setVisible(true);
    }//GEN-LAST:event_mnuLoginActionPerformed

    private void mnuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroActionPerformed
        new Cadastrar().setVisible(true);
    }//GEN-LAST:event_mnuCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAvaliacao;
    private javax.swing.JMenuItem itmEventos;
    private javax.swing.JMenuItem itmIngressos;
    private javax.swing.JMenuItem itmProgramacao;
    private javax.swing.JMenuItem itmSubmissao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCadastro;
    private javax.swing.JMenuItem mnuLogin;
    private javax.swing.JMenu mnuMenu;
    // End of variables declaration//GEN-END:variables
}
